######################################################################
# Automatically generated by qmake (2.01a) Thu May 11 12:04:57 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += buttongroup.cpp
