######################################################################
# Automatically generated by qmake (2.01a) Thu May 11 12:52:14 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += linguist.cpp
TRANSLATIONS = linguist_fr_FR.ts   \
               linguist_en_US.ts   \
               linguist_tr_TR.ts
